let shopItemsData = [
    {
      id: "ckr1",
      name: "Moi Moi with Custard",
      price: 500,
      img: "./assets/images/menu-1.png",
    },
    {
      id: "ckr2",
      name: "Ewa agoyin with Bread",
      price: 1000,
      img: "assets/images/menu-2.png",
    },
    {
      id: "ckr3",
      name: "Fried Plantain and Yam with Egg Stew",
      price: 250,
      img: "./assets/images/menu-3.png",
    },
    {
      id: "ckr4",
      name: "Afang Soup and Semo",
      price: 300,
      img: "./assets/images/menu-4.png",
    },
    {
      id: "ckr5",
      name: "Egusi and Pounded Yam",
      price: 500,
      img: "./assets/images/menu-5.png",
    },
    {
      id: "ckr6",
      name: "Fried Rice and Chicken",
      price: 500,
      img: "./assets/images/menu-6.png",
    },
    // {
    //   id: "ckr7",
    //   name: "Sausage-rolls",
    //   price: 1000,
    //   img: "images/pork-sausage-rolls.jpg",
    // },
    // {
    //   id: "ckr8",
    //   name: "Tasty-cinnamon-buns",
    //   price: 250,
    //   img: "images/tasty-cinnamon-buns.jpg",
    // },
    // {
    //   id: "ckr9",
    //   name: "Buns",
    //   price: 300,
    //   img: "images/buns.jpg",
    // },
    // {
    //   id: "ckr10",
    //   name: "Croissant",
    //   price: 300,
    //   img: "images/croissant.jpg",
    // },
    // {
    //   id: "ckr11",
    //   name: "Yummy Croissant",
    //   price: 500,
    //   img: "images/croissant2.jpg",
    // },
    // {
    //   id: "ckr12",
    //   name: "Meat-pie",
    //   price: 1000,
    //   img: "images/meat-pie.jpg",
    // },
    // {
    //   id: "ckr13",
    //   name: "Sweet-cake",
    //   price: 250,
    //   img: "images/sweet-cake.jpg",
    // },
    // {
    //   id: "ckr14",
    //   name: "Assorted-donuts",
    //   price: 300,
    //   img: "images/assorted-donuts.jpg",
    // },
    // {
    //   id: "ckr15",
    //   name: "Vintage-cupcakes",
    //   price: 300,
    //   img: "images/vintage-cupcakes.jpg",
    // },
    // {
    //   id: "ckr16",
    //   name: "Colorful-cupcakes",
    //   price: 500,
    //   img: "images/colorful-cupcakes.jpg",
    // },
    // {
    //   id: "ckr17",
    //   name: "Chocolate-cake",
    //   price: 1000,
    //   img: "images/chocolate-cake.jpg",
    // },
    // {
    //   id: "ckr18",
    //   name: "Cupcakes",
    //   price: 250,
    //   img: "images/cupcakes.jpg",
    // },
    // {
    //   id: "ckr19",
    //   name: "Hot-dog-buns",
    //   price: 300,
    //   img: "images/hot-dog-buns.jpg",
    // },
    // {
    //   id: "ckr20",
    //   name: "Hamburger-buns",
    //   price: 300,
    //   img: "images/hamburger-buns.jpg",
    // },
    // {
    //   id: "ckr21",
    //   name: "Crusty-baguettes",
    //   price: 300,
    //   img: "images/crusty-mini-baguettes.jpg",
    // },
    // {
    //   id: "ckr22",
    //   name: "Hot-burgers",
    //   price: 300,
    //   img: "images/hot-burgers-french-fries.jpg",
    // },
    // {
    //   id: "ckr23",
    //   name: "hot-cross-buns",
    //   price: 300,
    //   img: "images/hot-cross-buns.jpg",
    // },
    // {
    //   id: "ckr24",
    //   name: "assorted-donuts-carnival",
    //   price: 300,
    //   img: "images/assorted-donuts-carnival.jpg",
    // },
    // {
    //   id: "ckr23",
    //   name: "Donuts",
    //   price: 300,
    //   img: "images/donuts1.jpg",
    // },
    // {
    //   id: "ckr24",
    //   name: "Donuts-in-box",
    //   price: 300,
    //   img: "images/delicious-donuts-in-box.jpg",
    // },
    // {
    //   id: "ckr25",
    //   name: "Delicous-donuts",
    //   price: 300,
    //   img: "images/colorful-donuts.jpg",
    // },
    // {
    //   id: "ckr26",
    //   name: "Chocolate-cookies",
    //   price: 300,
    //   img: "images/chocolate-cookies.jpg",
    // },
    // {
    //   id: "ckr27",
    //   name: "Dessert-cream-chocolate",
    //   price: 300,
    //   img: "images/dessert-cream-chocolate.jpg",
    // },
    // {
    //   id: "ckr28",
    //   name: "Strawberry-layered-dessert",
    //   price: 300,
    //   img: "images/layered-dessert.jpg",
    // },
  ];
  